CMakeLists.txt, README.md, cmake/CPM.cmake, cmake/GetDependencies.cmake
This commit improves the cmake step to optionally
download genh5 and logging to simplify building gtlab.
Also, a first draft of the new readme is updated.
Closes #1088
/label ~InProgress
=> Improve cmake and updates readme

.github/workflows/ci.yml
This adds a Github Action to create the developer documentation.
Currently, the documentation is stored as a build artifact only.
Later, when the documentation has been finished, we should deploy
it to a website, e.g. github pages.
See the CI results....
Closes #1099
=> Added CI for documentation

docs/concept.rst
Closes #1117
This is almost a 1:1 migration of the property documentation from our wiki. I did not yet include screenshots of the property dock widget though.
=> Migrated the property documentation

.readthedocs.yml, .reuse/dep5, docs/requirements.txt
This PR adds a "readthedocs" integration. This service automatically builds the documentation, when the repo has changed and also hosts the HTML pages.
https://gtlab.readthedocs.io/en/latest/index.html
=> Host and build documentation on readthedocs

README.md, docs/conf.py, docs/static/css/custom.css
Small change to make the logo not appear in the readme section, since it will be already shown in the sidebar.
I also created a DOI and added the badge in the Readme: [DOI: 10.5281/zenodo.10666587](https://doi.org/10.5281/zenodo.10666587)
=> Remove logo in readme text in docs

src/core/process_management/gt_processcomponent.cpp, src/core/process_management/gt_processcomponent.h
For the usage of calculators in the graph system (outside the original process management) it is necessary to fill the list of linkable objects to be able to work with object links.
This is done by an additional function which enables to add objects to this list
Usage in the graph system
=> implementation to add object to list of linkable objects

CHANGELOG.md, src/core/process_management/gt_taskgroup.cpp, src/dataprocessor/gt_xmlutilities.cpp
GTlab assumes a UTF-8 encoding. However, tasks have been saved using the default ANSI encoding. Thus, when reading in a task, the unicode characters were misinterpreted.
Now, tasks and other xml files are forced to be written as UTF-8.
Fixes #1125
Manually using the following steps:
- Create a python tasks
- Insert `print("°")`
- Save & close the project 
- Reopen the project and open the task
The `°` character should be still the same and not replace by `?`.
=> Fixed encoding of tasks

CHANGELOG.md, src/core/gt_projectanalyzer.cpp
The widget entries for unknown classes is only shown in dev mode
=> Activate warning for unknown classes only in dev mode

CHANGELOG.md, src/app/dock_widgets/output/gt_outputdock.cpp
Closes #606.
Applied a highlighted effect to the filter buttons if they are enabled
Manually
=> Resolve "Active/Inactive filter buttons of output dock widget are hard to distinguish in dark mode"

CHANGELOG.md, src/batch/CMakeLists.txt, src/batch/batch.cpp, src/batch/gt_consolerunprocess.cpp, src/batch/gt_consolerunprocess.h
If a task is organized in a task group which might not be the default group (normally the users group) the task cannot be executed in the console application.
This is fixed in this PR.
Call the run function now as following:
GTlabConsole run <PROJECT_ID> <TASK_ID> <TASK_GROUP_ID> (last one is optional)
If the given <TASK_GROUP_ID> is not empty the task group is switched to the given group and the task is searched and if found executed. 
For a cleanup of the batch the functions related to process execution are extracted to new files in a new namespace.
Manual tests of execution of a task which is part of another task group
=> Make tasks groups executable from console

CHANGELOG.md, src/app/dock_widgets/output/gt_outputdock.cpp, src/app/dock_widgets/output/gt_outputdock.h
Closes #1136
Workaround by calling copy method explicitly in keyevent of output dock (see issue #1175 for future fix)
=> Resolve "Copying Multiple Messages from Output Dock using Keyboard Shortcuts does not work sometimes"

src/app/dock_widgets/properties/gt_propertycontainerwidget.cpp, src/gui/dock_widgets/properties/gt_propertymodel.cpp
Closes #568
This PR reduces the command  scopes from the project to the actual GtObject, when property container are modified, i.e. entries are removed and added.
I tested  it in the GUI, undo/redo still works when changing the container entries.
=> Reduced  scopes for property container entries

src/app/dock_widgets/process/gt_processdock.cpp, src/app/dock_widgets/process/gt_processdock.h, src/app/dock_widgets/process/gt_processview.cpp, src/app/dock_widgets/process/gt_processview.h
Multiple elements of the same parent can be moved (to another task or a different position in the same task)
the process view re implemented the drop event which emits a signal. This is connected to a slot in the process dock.
There the list of selected items and the target are checked for validity and the move is performed
By usage in the GUI
=> Move multiple elements in the process dock widget

src/gui/dock_widgets/process/gt_processcomponentmodel.cpp
There is an error message implemented (currently not apperaing anymore, which logged some fatal lines but only in devmode.
This is now changed to logging also in non-dev-mode but only with gtDebug as it is a message for debugging.
Cannot reproduce occurance so cannot test
=> Fix "Move rows failed" error message

src/core/process_management/gt_processmoduleloader.cpp
As mentioned in the issue description the tasks of the modules were registered twice as seen by a warning in the logging.
This double registration was caused by a doubled execution of the registerClass function of the objectFactory
This was removed
I removed the second call of the registration
I started GTlab. My processes worked fine while the warning in the logging system did not appear anymore
=> Remove duble registration of tasks

src/gui/importer/gt_importmenu.cpp
Closes #1188
- I first checked, that the command is actually used by commenting it out: Undo was not available, great!
- Then you changed the code to use the enclosing object, Undo is working again 😄
=> Reduced scope of the import menu command

src/dataprocessor/gt_eventloop.cpp, tests/unittests/datamodel/test_gt_eventloop.cpp
Closes #1154 
Fixed `GtEventLoop` not returning if timeout was set to 0.
- Checked usages of `GtEventLoop`
- Added Unittests
=> Resolve "fix GtEventLoop running indefintely if timeout was set to 0"

src/app/dock_widgets/process/gt_processdock.cpp
The scope for the change commands in the process dock are changed to not use the whole currentProject but 
The commands to determine the changes to keep in the undo/redo system got a more specific scope: the current selected task group
I startet GTlab with a project with multiple task groups and tasks in it. I did several actions like moving, copy, paste, ... and no problem occured but undo was possible.
=> Reset scope for undo_redo commands in process dock

CHANGELOG.md, src/app/ui/gt_mainwin.ui, src/gui/CMakeLists.txt, src/gui/widgets/gt_tabwidget.cpp, src/gui/widgets/gt_tabwidget.h
Allowed mdi items to be closed using middle mouse click. Closes #603
Manually.
=> Resolve "Allowed mdi items to be closed using middle mouse click"

CHANGELOG.md, src/gui/gt_textfilterdelegate.cpp
Closes #523. 
Objects that have no dedicated `GtObjectUI` associated, were more restrictive when renaming in the explorer (e.g. no space allowed). This was fixed by using a fallback `GtObjectUI`. 
Manually.
=> Resolve "Renaming objects in the explorer fails sometimes if the new name contains spaces"

.gitlab-ci.yml, src/app/dock_widgets/output/gt_outputdock.cpp, src/app/dock_widgets/process/gt_processdock.cpp, src/app/preferences/pages/gt_preferencesapp.cpp, src/gui/dialogs/project_settings/gt_projectsettingsgeneraltab.h
This fixes all code problems discovered by cppcheck.
In addition:
- Adjusted the pipeline that the cppcheck job fails, if new errors occur (note, that this is a change in our ci templates)
- Don't allow failure of the job anymore
- See commit history
=> Fix cppcheck warnings / errors

src/batch/CMakeLists.txt, src/batch/batch.cpp
The console application now uses the GtApplication and not only the GtCoreApplication. This was required as the collections had been read from the interfaces in the mdiLauncher which is not accessible in the CoreApplication.
This is a work around as the core application should normally depend on GUI elements
The colleague who asked for the change used it successfully.
=> Enable console application to use collections

src/gui/gt_mdilauncher.cpp
=> Hide button to detach mdi widget in non dev mode

src/batch/batch.cpp, src/core/gt_coreprocessexecutor.cpp, src/core/gt_processexecutormanager.cpp, src/core/process_management/gt_taskrunner.cpp, src/gui/gt_application.cpp, src/gui/gt_shortcuts.cpp
This commit switches back the executor to the coreexecutor. This change is required, since the batch app has no event loop and thus cannot handle running tasks in threads correctly.
Thanks at @real-ct-ac for digging into it in depth.
Fixed #1233 
Note: In a second commit, I removed many annoying warnings (or  changed the logging level).
This bug first revealed on  python calculators, which crashed or failed to run. 
I tested these changes with
- Empty tasks
- Tasks with Python calculators
- On Windows and Linux
This change seems to restore the old functionality.
=> Fixed empty task bug on console app

src/batch/gt_consolerunprocess.cpp
This PR runs a "GTlabConsole run -f <projectfile>" in a temporary session.
This improves usage in regression tests without any side effect to the current session.
Closes #1248
With local tests.
=> Run the console command in a temp session

CHANGELOG.md, src/batch/batch.cpp, src/core/gt_session.cpp
Fixed bug introduced in 2.0.7, that "GTlabConsole run" does not save projects anymore. This change reverts
a commit in 2.0.7 that allowed to use the collections from batch mode.
__NOTE: collections will stop working in batch mode again__
Closes #1247
On the console. We will need to create regression tests to check this in future.
=> [CRITICAL] Fixed bug: Save project via "GTlabConsole run" does not work anymore

CHANGELOG.md, src/core/CMakeLists.txt, src/core/process_management/calculators/gt_exporttomementocalculator.cpp, src/core/process_management/calculators/gt_exporttomementocalculator.h, src/core/process_management/gt_calculatorfactory.cpp
Added a new calculator to be able to export user selected data objects from current project.
The objects are exported in Memento-Format (XML).
Users can select whether the object is exported to an absolute or relative file path .
The relative file path can be related to the project directory or the working directory.
Missing subdirectories are created automatically.
The calculator is currently required specifically for regression tests.
It fixes issue #1251
The calculator was tested manually in all three modes.
=> added new calculator to export specific data object to hard disk

CHANGELOG.md, src/batch/gt_consolerunprocess.cpp
1. Fixed "GTlabConsole run -f project.gtlab -s" not saving changes to the project
2. Fixed task group argument ignored in batch command "GTlabConsole run -f project.gtlab"
The reason for problem 1. was, that the process executor was setup to do a dry run, 
resulting in not merging back the changed memento, allthough the project was technically saved.
The reason for problem 2. was, that the argument "GroupID" was simply not used accidentally.
To avoid these problems in future, I changed the code to reuse the existing function `runProcess`.
Local Changes and in Sketchpad regression tests.
=> Fixed multiple problems in batch commonad "gtlabconsole run -f ..."

src/gui/mdi_items/collection_env/gt_localcollectionmodel.cpp
The check for additional parameters to use for sorting is moved to the relevant section and not done default.
Manual as sorting is now possible by name for material collection as it was not before
=> Fix sort for collection items without additional parameters

CHANGELOG.md, CMakeLists.txt, conanfile.py, src/core/gt_coreapplication.cpp, src/core/gt_project.cpp, src/dataprocessor/gt_package.cpp, src/dataprocessor/gt_package.h, src/dataprocessor/gt_version.h
Closes #617
__ ABI CHANGE__
- Added new package read/write functions to store miscelleneous data, like intelligraphs etc.
- The new functions are directly executed after calling the xml-based ones.
- Using the new APi, the currentProject()->path workaround can be avoided, which is error prone.
- Modules, that don't exploit this functionality require only a recompile
- Other modules (like intelligraph) should be adapted to use this new API
@mariusalexander I quickly adapted locally the intelligraph package to test this. Seems to be working.
Please still have a look!
Locally, with an adapted intelligraph.
=> Added project dir to package read/save api

CHANGELOG.md, src/app/dock_widgets/process/gt_processdock.cpp
This fixes the regression from 2.0.5, that deleting multiple process elements results in a crash.
The regression came from commit https://github.com/dlr-gtlab/gtlab-core/commit/37383d9c2e3b042d76ce645731d48bd6f54def0d, which had a incorrect refactoring in the end.
The change makes sure, that the single selection is not processed, when the multi-selection is handled.
1. Create two calculators
2. Delete them via context menu. 
3. Without the change, the app crashed (in debug mode at least). Now, everything is fine again.
=> Fix crashes when two tasks / calculators are deleted

CHANGELOG.md, src/app/dock_widgets/process/gt_processdock.cpp, src/app/dock_widgets/process/gt_processdock.h, src/app/dock_widgets/process/gt_processview.cpp, src/app/dock_widgets/process/gt_processview.h
The function to skip or unskip elements via a shortcuts is extended to be used for selection of more of one element.  
There is added a very small cleanup to reduce code. 
Manual tests
=> Enable skip/unsik hotkey for multiple elements

CHANGELOG.md, src/app/preferences/pages/gt_preferencesshortcuts.cpp, src/gui/widgets/gt_shortcutedit.cpp, src/gui/widgets/gt_shortcutedit.h
Adding GtShortCutEdit as an Item to The Table and Implemented a special comparison method for sorting the entries according to the ShortCut-String.
Closes https://github.com/dlr-gtlab/gtlab-core/issues/482
Worked in local GTlab instance.
=> feat.: Enable Sorting for QLineEdits in Preference View

CHANGELOG.md, src/gui/tools/gt_environmentmodel.cpp
- Return String for QLineEdit in displayCase for the QTableView
- Existing text can now be selected
=> Fix deletion of environment variables when trying to edit it via settings dialig

CHANGELOG.md, src/core/gt_objectfiltermodel.cpp, src/core/gt_treefiltermodel.cpp, src/core/gt_treefiltermodel.h, src/gui/dock_widgets/process/gt_processfiltermodel.cpp, src/gui/gt_styledmodel.cpp
This improves the performance of the object link selection (`GtObjectFilterModel`).
The reason for the slow performance was a ping-pong of virtual calls between the `GtObjectFilterModel`and `GtTreeFilterModel`.
As a result, childs were unnecessary often traversed, resulting in an exponential decay in runtime.
The solution was to write the traversing logic in a function that also accept another predicate function checking, if an object is accepted. This avoids ping-ponging and excessive child traversal.
As a result, the implementation of `GtObjectFilterModel`and `GtProcessFilterModel` is now very short.
Closes #1206 
Local tests.
=> Major performance improvement of objectlink object selection 

CHANGELOG.md, src/dataprocessor/property/gt_enumproperty.h, tests/unittests/datamodel/test_gt_enumproperty.cpp
In GitLab by @NelDav on Oct 27, 2023, 08:06
Closes #609
=> Resolve "GtEnumProperty::setValueFromVariant should fail in case the variant is not a valid enum value."

src/app/dock_widgets/process/gt_processconnectioneditor.cpp, src/app/dock_widgets/process/gt_processconnectioneditor.h, src/app/mdi_items/process_env/entities/gt_processconnectionview.cpp, src/app/mdi_items/process_env/entities/gt_processconnectionview.h, src/app/mdi_items/process_env/entities/gt_processpropertyconnectionentity.cpp, src/app/mdi_items/process_env/entities/gt_processpropertyconnectionentity.h, src/app/mdi_items/process_env/entities/gt_processpropertyportentity.cpp, src/app/mdi_items/process_env/gt_processconnectiongraphicsview.cpp, src/app/mdi_items/process_env/gt_processconnectiongraphicsview.h, src/app/mdi_items/process_env/gt_processconnectionmodel.cpp, src/app/mdi_items/process_env/gt_processconnectionmodel.h, src/app/mdi_items/process_env/gt_processconnectionscene.cpp, src/gui/gt_colors.cpp, src/gui/gt_colors.h
The new button removes all graphics entities for the connections and the related connection objects.
Manual
=> Remove all connections at once by button

src/gui/gt_application.cpp
remove warnings for creation of multiple commands. These are recorded in the command stack.
Thus the warnings are unneccessary.
=> fix.: remove warnings for creation of multiple commands. These are recorded in the command stack

CHANGELOG.md, src/gui/object_ui/gt_projectui.cpp
Projects cannot be switched while task is running. This PR removes the possibility to switch to the same project while a task is running/does not show the project switch warning in this case.
=> fix.: disabled switching project to same project while task is running

src/gui/gt_colors.cpp, src/gui/gt_colors.h
To improve the ability for a single look in GTlab some colors for schedules and splines are added to the colors namespace
=> Add some basic colors for plotting for splines and schedules

src/dataprocessor/property/gt_doubleproperty.cpp, src/dataprocessor/property/gt_doubleproperty.h, src/dataprocessor/property/gt_intproperty.cpp, src/dataprocessor/property/gt_intproperty.h, src/dataprocessor/property/gt_stringproperty.cpp, src/dataprocessor/property/gt_stringproperty.h, tests/unittests/datamodel/test_gt_doubleproperty.cpp, tests/unittests/datamodel/test_gt_intproperty.cpp, tests/unittests/datamodel/test_gt_stringproperty.cpp
Basic implementation of some operators for +=, -=, ... 
These are now implemented for double, int and string property
=> Operators for double int and string propeties

src/core/gt_globals.h, src/core/process_management/gt_task.cpp, src/core/process_management/gt_task.h
The function was not used and therefore could be removed
=> Deprecate unused run function of GtTask

src/app/dock_widgets/process/gt_processdock.cpp, src/app/dock_widgets/process/gt_taskgroupmodel.cpp, src/app/mdi_items/examples/gt_examplesmdiwidget.cpp, src/core/gt_coredatamodel.cpp, src/core/gt_coredatamodel.h, src/gui/dialogs/project_upgrader/gt_projectupgradesettingspage.cpp, src/gui/dock_widgets/process/gt_processcomponentmodel.cpp, src/gui/gt_datamodel.cpp, src/gui/object_ui/gt_projectui.cpp
Deprecation of the unique object name function in the core datamodel to reduce access to the datamodel instance if it is not needed
=> Deprecate unique object name

src/core/gt_datamodelinterface.h, src/core/gt_globals.h, src/core/gt_moduleinterface.h, src/core/gt_moduleloader.cpp, src/core/gt_moduleloader.h, src/core/process_management/gt_processmoduleloader.cpp, src/dataprocessor/gt_qtutilities.h, src/gui/gt_guimoduleloader.cpp
This PR also increases the datamodel interface version, as the GtPackage ABI was changed in a previous PR.
Closes #1273
- added function `checkInterface`  to test interface compatibility
- added macro `GT_OLD_INTERFACES` to define previous interface versions that are used to test a module against
I tried to load e.g. basictools, which is now denied. When though building basictools from scratch against this version, it will load.
Here's an example, when GTlab does not load the TestDMI module, as it was compiled against 2.0:
=> Add functionality to test module interface versions

src/app/app.cpp, src/app/preferences/pages/gt_preferencesshortcuts.cpp, src/core/settings/gt_settings.cpp, src/core/settings/gt_settings.h, src/core/settings/gt_shortcutsettingsdata.cpp, src/core/settings/gt_shortcutsettingsdata.h, src/gui/gt_application.cpp, src/gui/gt_application.h, src/gui/gt_dockwidget.cpp, src/gui/gt_dockwidget.h, src/gui/gt_mdiitem.cpp, src/gui/gt_mdiitem.h, src/gui/gt_objectui.cpp, src/gui/gt_objectui.h, src/gui/gt_objectuiaction.cpp, src/gui/gt_shortcut.cpp
The core has a dependency to the QtGUI library only because of the usage of the QKeySequence to store ShortCut information.
This is changed in this PR. The GtShortCutSettingsData now stored the key information in a QString. This is an ABI change!
And as also the constructor changes this is also an API change!
First overview in our modules showed there would be the need in 2 modules to make simple adaptions but external module developers might be affected as well if they use short cuts with this old interface.
As the transfer from keySequence to string and vice versa could lead to wrong usage the interface was extended to avoid the usage of the  GtShortCutSettingsData for module developers but use interface functions still have the option to use keysequences to store the used keys.
First a …
=> Try to use QString instead of keysequence to avid Gui dependency

CHANGELOG.md, src/app/gt_mainwin.cpp, src/gui/gt_mdiitem.cpp, src/gui/gt_mdiitem.h, src/gui/gt_qmlaction.cpp, src/gui/gt_qmlaction.h, src/gui/tools/gt_qmltoolbargroup.cpp, src/gui/tools/gt_qmltoolbargroup.h, src/resources/qml/AnimatedButton.qml, src/resources/qml/Toolbar.qml, src/resources/qml/ToolbarButton.qml, src/resources/qml/ToolbarSeparator.qml, src/resources/qml/qml.qrc, tests/modules/mdi_interface_ext/mdi/test_mdi_ext_viewer.cpp, tests/unittests/gui/test_toolbargroup.cpp
I implemented more toolbar features, namely
- Toolbar separators
- Actions, that can be toggled
Separators are not show, if not necessary, e.g. if all actions left or right from the separator are invisible.
- Both features have been implemented in the mdi test module
- I added unit tests for separator visibiliry
Dark-mode:
Bright-mode:
Closes #1310
=> Implemented toolbar separators and toggle actions

CHANGELOG.md, src/batch/CMakeLists.txt, src/batch/batch.cpp, src/batch/gt_consolerunprocess.cpp, src/batch/gt_consolerunprocess.h, src/batch/gt_consoleupgradeproject.cpp, src/batch/gt_consoleupgradeproject.h, src/core/gt_project.cpp, src/core/gt_project.h, src/gui/object_ui/gt_projectui.cpp
It is now possible to update projects with batch commands.
The new commands are: 
-    .\GTlabConsole.exe upgrade_project c:\data\my_project
-   .\GTlabConsole.exe upgrade_project c:\data\my_project -o c:\data\my_new_project
Exact information can be viewed by 
`GTlabConsole.exe upgrade_project --help`
Closes #1184
MS: Since the code now affects gui and batch mode, I tested both with an intelligraph update for also the two cases
- Inplace upgrade
- Save to a new project path
All 4 cases are successful.
=> feat.: Adding Update Project Procedure to Batch-Mode

src/dataprocessor/CMakeLists.txt, src/dataprocessor/gt_regexp.cpp, src/dataprocessor/property/gt_stringproperty.cpp, src/dataprocessor/property/gt_stringproperty.h, src/gui/dock_widgets/properties/items/gt_propertyitem.cpp, tests/unittests/datamodel/test_gt_object.h
Usage of QValidator is the last reason for the core libraries (DataProcessor and Core) to have a dependency to QtGUI.
The QValidator is replaced by a string to hold the validator pattern.
As it is part of the GtStringProperty the needed changes leads to ABI and API breaks.
Manual in the GTlab GUI
=> Replace QValidator by RegExpPattern-String

CHANGELOG.md, src/dataprocessor/property/gt_doubleproperty.cpp, src/dataprocessor/property/gt_doubleproperty.h, src/dataprocessor/property/gt_intproperty.cpp, src/dataprocessor/property/gt_intproperty.h
Double and Int-Property already had flags as private member if the bounds are active or not.
Now there are getter to request these states
Simple getter functions had been added.
Closes #1327
=> Enable request if low and high bounds are active or not

src/app/gt_mainwin.cpp, src/gui/gt_application.cpp
Fixed the toolbar resize problem on app start.
Source of the issue was, that app perspective restore was happening simultaneously as the `themeChanged` event was thrown, leading to a theme update. Somehow, this resulted in a bad timing leading to a wrong resize.
I now moved the themeChanged event to the mainwindow code just before restoring the perspective, which seem to fix it for me.
Closes #1318
Manually.
=> Fixed toolbar resizing on app start

CHANGELOG.md, src/core/process_management/gt_processdata.cpp
This improves task group creation logging, which now displays the name of the created task group.
This allows users to debug, what groups they are using currently, in particular in a docker environment.
Closes #1341
Manually
=> Improve task group creation logging

src/core/settings/gt_abstractsettings.cpp
The previoius code created a memleak, if a
setting is registered multiple times.
In this case, the old pointer is discarded
and its memory is lost.
Now, we delete the old setting first.
Using AddressSanitizer (Clang) on Linux.
=> Fixed memory leaks when registering settings

src/gui/dock_widgets/properties/editors/gt_colorpropertyeditor.cpp
Fixed a small memory leak  in the editor of the color property. The line edit does not take ownership of the validator, 
hence we  give the ownership to the editor.
=> Fixed memleak in color property editor

src/app/dock_widgets/process/gt_processdock.cpp
=> Invalidate current index when the task group is changed

CHANGELOG.md, src/dataprocessor/gt_object.cpp, src/dataprocessor/gt_object.h, src/dataprocessor/property/gt_abstractproperty.cpp, src/dataprocessor/property/gt_abstractproperty.h, src/gui/dock_widgets/properties/gt_propertymodel.cpp, src/gui/dock_widgets/properties/gt_propertymodel.h, src/gui/dock_widgets/properties/gt_propertytreeview.cpp, src/gui/dock_widgets/properties/items/gt_propertycategoryitem.cpp, src/gui/dock_widgets/properties/items/gt_propertycategoryitem.h, src/gui/dock_widgets/properties/items/gt_propertyitem.cpp
Closes #1344
This allows to configure the position and the expand state of property groups. 
- Each group can be assigned to a priority. The higher it is, the lower the group will be positioned
- The main group comes always first (by default), which has a priority of 1
- It is implemented by modifying the group names internally, thus there is no ABI break
Manually.
=> Configurable property locations and expand states

src/core/gt_moduleloader.cpp, tests/modules/mdi_interface_ext/test_mdi_interface_ext.json
If a regex should be used, the identifier must start with "regex:".
I also added a check for module dependency cycles.
The `mdi interface ext` module now uses a regex to define its dependency to the "data model interface" module.
=> Allow for module dependency regexes

src/dataprocessor/gt_abstractobjectfactory.cpp, src/dataprocessor/gt_abstractobjectfactory.h
Closes #1343 - marked destructor as virtual
=> Resolve: "Destructor of GtAbstractFactory not marked as virtual"

src/gui/gt_application.cpp
Fixes #1357 
Now, the python interpreter query is printed after theme switching, see:
=> Fixed zombie theme during module initialization

.github/workflows/ci.yml
Github does not support windows server 2019 anymore. So I upgraded to 2022.
=> Try to fix github ci

src/core/process_management/calculators/gt_exporttomementocalculator.cpp
The label is not used in the calculator and so should be hidden
=> Hide irrelevant label for only calculator of core system

CHANGELOG.md, src/app/dock_widgets/output/gt_outputdock.cpp, src/app/dock_widgets/output/gt_outputdock.h
Closes #1260 - fixed output dock not resizing new rows correctly
Manually. No performance degradation of the GUI (e.g. stuttering) was noted compared to the previous version
=> Resolve "Output dock does not resize new rows that span multiple lines"
