docs/building.rst
Closes #1100
Added build instructions to developer documentation.
/label ~InProgress
=> Added build instructions

docs/conf.py, docs/requirements.txt
=> Improved visual style for documentation

docs/api.rst, docs/conf.py, docs/faq.rst, docs/index.rst, docs/requirements.txt
I migrated parts of the FAQ from the wiki.
There are stille FAQs, that need to be extracted from mattermost etc.
Closes #1109
=> Added FAQ section

src/app/dialogs/gt_logerrormessagebox.cpp, src/app/dock_widgets/process/gt_processdock.cpp, src/app/widgets/gt_splashscreen.cpp, src/gui/style/gt_palette.cpp
Fixes #1137
There were a couple of memleaks in the Gui library and in the main application. Resulting in pretty large leaks.
With these fixes, the leaks are much smaller:
```
=================================================================
==19087==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 6656 byte(s) in 26 object(s) allocated from:
#0 0x7f958c0a0330 in __interceptor_malloc (/lib/x86_64-linux-gnu/libasan.so.5+0xe9330)
#1 0x7f9580a9a6d4  (/lib/x86_64-linux-gnu/libfontconfig.so.1+0x206d4)
Indirect leak of 1632 byte(s) in 51 object(s) allocated from:
#0 0x7f958c0a0518 in calloc (/lib/x86_64-linux-gnu/libasan.so.5+0xe9518)
#1 0x7f9580a9ad18  (/lib/x86_64-linux-gnu/libfontconfig.so.1+0x20d18)
Indirect leak of 519 byte(s) in 50 object(s) allocated from:
#0 0x7f958bff1810 in …
```
=> Fixed some memory leaks

src/dataprocessor/property/gt_enumproperty.h, tests/modules/datamodel_interface/data/test_dmi_data.cpp, tests/modules/datamodel_interface/data/test_dmi_data.h, tests/unittests/datamodel/test_gt_enumproperty.cpp, tests/unittests/datamodel/test_gt_enumproperty.h
added support for scoped enums to `gtEnumProperty` and added some unit tests
Closes #1146
=> fix: scoped enums for gt_enumproperties

src/app/gt_mainwin.cpp
=> change path to github

src/gui/dock_widgets/properties/gt_propertymodel.cpp
=> Add type information to property container elements as tooltip

src/gui/style/gt_palette.cpp
=> Fixed buggy widget style application

.github/ISSUE_TEMPLATE/BUG-REPORT.yml
=> Issue templates

CHANGELOG.md, src/gui/tools/gt_pyhighlighter.cpp
Just a small fix to avoid copies in for loops, which turned out to be a hot spot in the syntax highlighter.
This is just a part of the performance fix. The rest need to be done in the python module itself.
Fixes #1139
Manually and via Performance Analysis in Visual Studio.  Before, the for loop took a significant amount of the computing time.
=> Improve performance of python console output

src/app/dock_widgets/process/gt_processdock.cpp, src/app/dock_widgets/process/gt_processdock.h
In GitLab by @jensschmeink on Sep 5, 2023, 09:42
Closes #580
=> Resolve "Processes/Calculators-Area makes it difficult to add new taks"

tests/guitests/gtlab_core_tests/gtlab_core_gui_tests/tst_Dock_Processes/test.feature
=> Fix GUI tests failure in process dock widget

CHANGELOG.md, src/core/gt_project.cpp, src/core/gt_project.h, src/core/gt_session.cpp, src/core/gt_session.h, src/gui/CMakeLists.txt, src/gui/dialogs/project_settings/gt_projectsettingsdialog.cpp, src/gui/dialogs/project_settings/gt_projectsettingsgeneraltab.cpp, src/gui/dialogs/project_settings/gt_projectsettingsgeneraltab.h, src/gui/gt_datamodel.cpp, src/gui/tools/gt_projectanalyzerdialog.cpp, src/gui/tools/gt_projectanalyzerdialog.h
=> 1162 project error report widgets should be mutable by states

src/app/dock_widgets/process/gt_processdock.cpp, src/app/dock_widgets/process/gt_processdock.h, src/gui/gt_application.cpp
=> Fix moving process element bug

.gitlab-ci.yml, tests/unittests/CMakeLists.txt
=> CTest setup

tests/unittests/CMakeLists.txt
=> Fix discover Test

src/batch/gt_consolerunprocess.cpp
=> error message in gt_consolerunprocess.cpp

src/batch/batch.cpp, src/batch/gt_consolerunprocess.cpp
Help messages: remove typos and add clarifications
=> Console help messages: minor changes

src/core/process_management/gt_taskgroup.cpp
=> Fixed non-deterministic task serialization

.github/workflows/ci.yml, .reuse/dep5, CMakeLists.txt, cmake/CPM.cmake, cmake/GetDependencies.cmake, cmake/logging.patch, tests/unittests/datamodel/test_varianthasher.cpp, vcpkg-configuration.json, vcpkg.json
This PR builds and tests GTlab using the Github Actions pipelines on windows and ubuntu.
Build and Tests are not yet separate jobs, but I already works.
=> First try to build GTlab with actions

CHANGELOG.md, src/app/app.cpp
=> Fix scaling problems on windows for screen scaling settings 150%

CHANGELOG.md, src/dataprocessor/property/gt_unit.cpp, src/dataprocessor/property/gt_unit.h, src/dataprocessor/property/gt_unitconverter.h, tests/modules/datamodel_interface/data/test_dmi_data.cpp, tests/modules/datamodel_interface/data/test_dmi_data.h, tests/unittests/datamodel/test_gt_unitconverter.cpp
=> Add few electrical units

CHANGELOG.md, src/app/mdi_items/process_env/entities/gt_processpropertyportentity.cpp
=> Allow connecting GtStringMonitoringProperty to GtStringProperty
